### ISSUE TITLE
NoClassDefFoundError when user selects 'Recent Changes' from drop-down menu

### ISSUE THREAD

**Issue by ghost** [fitnesse/fitnesse-git-plugin#17]
My FitNesse server 20200501 starts up correctly with fitnesse-git-plugin 1.2.0 loaded.

`PS D:\FitNesse> java -jar fitnesse-standalone.jar
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 80`

When user selects 'Recent changes' on a FitNesse wiki page, there is an error in the console.

`WARNING: Unexpected exception [org/apache/commons/lang/NotImplementedException]
java.lang.NoClassDefFoundError: org/apache/commons/lang/NotImplementedException
        at fitnesse.wiki.fs.GitFileVersionsController.toWikiPage(GitFileVersionsController.java:252)
        at fitnesse.responders.WikiPageResponder.loadPage(WikiPageResponder.java:46)
        at fitnesse.responders.WikiPageResponder.makeResponse(WikiPageResponder.java:36)
        at fitnesse.FitNesseExpediter.createGoodResponse(FitNesseExpediter.java:145)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:112)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.NotImplementedException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 11 more`

My plugins.properties content is
`VersionsController=fitnesse.wiki.fs.SimpleFileVersionsController
RecentChanges=fitnesse.wiki.fs.GitFileVersionsController`

**Comment by fhoeben** [comment]
I suspect the plugin must be updated to use the more recent Apache commons lang that is included in FitNesse since a couple of versions.
