### ISSUE TITLE
unable to load plugin class not found error

### ISSUE THREAD

**Issue by mcgowanb** [fitnesse/fitnesse-git-plugin#9]
I've followed the guide to install this plugin with fitnesse and I'm getting a class not found error. When I run `java -jar fitnesse-standalone.jar` I get the following output

```
SEVERE: Error while starting the FitNesse [Unable to instantiate component for type fitnesse.wiki.fs.FileSystemPageFactory]
fitnesse.components.ComponentInstantiationException: Unable to instantiate component for type fitnesse.wiki.fs.FileSystemPageFactory
	at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:81)
	at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:57)
	at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:100)
	at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.java:106)
	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:72)
	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:59)
	at fitnesseMain.FitNesseMain.main(FitNesseMain.java:39)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:75)
	... 6 more
Caused by: fitnesse.components.ComponentInstantiationException: Unable to look up component for type 'VersionsController' with classname 'fitnesse.wiki.fs.GitFileVersionsController'
	at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:53)
	at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:100)
	at fitnesse.wiki.fs.FileSystemPageFactory.<init>(FileSystemPageFactory.java:36)
	... 11 more
Caused by: java.lang.ClassNotFoundException: fitnesse.wiki.fs.GitFileVersionsController
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at fitnesse.components.ComponentFactory.lookupComponentClass(ComponentFactory.java:96)
	at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:49)
	... 13 more

```
Here is my directory structure,

```
.
├── FitNesseRoot
├── fitnesse-standalone.jar
├── plugins
│   └── fitnesse-git-plugin-1.2.0-all.jar
└── plugins.properties

```
can the contents of my plugins.properties
`VersionsController=fitnesse.wiki.fs.GitFileVersionsController
RecentChanges=fitnesse.wiki.fs.GitFileVersionsController`

**Comment by Romancha** [comment]
+, Have the same issues

**Comment by abailly** [comment]
Same here

**Comment by reprive** [comment]
I have the same issue, and I worked around it by explicitly putting the plugins folder in the classpath. That worked for me. I now start FitNesse as:

java -cp "c:\fitnesse\fitnesse.jar";"c:\fitnesse\plugins\*" fitnesseMain.FitNesseMain -p 8080 -d "c:\fitnesse"
